server:
  port: 10030
  servlet:
    context-path: /admin
spring:
  application:
    name: adminService
  cloud:
    nacos:
      server-addr: 192.168.147.130:8848
#      server-addr: 192.168.43.71:8848